### ISSUE TITLE
Space in title in Json break give command

### ISSUE THREAD

**Issue by TheoMarque** [BX-Team/NDailyRewards#78]
### Server Implementation

Paper

### Server Version

1.20.4 paper 389

### Describe the bug

After config reload if in name of item is space - plugin broke line in config.

### To Reproduce

Here is a command:

    commands:
    - 'console: give %player% minecraft minecraft:player_head{display:{Name:"{\"text\":\"Worek
      zboża\"}"},SkullOwner:{Id:[I;1314936643,545080562,-1445085535,-61748934],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGM4NTZiZDViMGY1ZmQyMDU2M2JmNjhiMWZlM2E1ODcyM2QzYWY5Y2FlZjg1OTIyMWM3ZWNmYTk2NDJmZjE5YiJ9fX0="}]}}}1'

space between Worek and zboża cause break in config. After save and reload - plugin parse again and break when find a space. 

### Expected behaviour

Not reparse config or proper behavior when space is in item name. Spaces in titles are allowed due treat them as string. 

### NDailyRewards Version

2.3.4

### Checklist

- [X] I have included a NDailyRewards error log.
- [X] I am using the newest build from https://modrinth.com/plugin/ndailyrewards and the issue still persists.

### Anything else?

No error log, not printed into console or something, just wrong command output. currently as workaround use escape a space \u0020 but this is not good idea.

**Comment by NONPLAYT** [comment]
so, I just tested it and all works perfectly with automatic line breaking. try using this:
```yaml
    commands:
    - 'console: give %player% minecraft:player_head{display:{Name:"{\"text\":\"Worek
      zboża\"}"},SkullOwner:{Id:[I;1314936643,545080562,-1445085535,-61748934],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGM4NTZiZDViMGY1ZmQyMDU2M2JmNjhiMWZlM2E1ODcyM2QzYWY5Y2FlZjg1OTIyMWM3ZWNmYTk2NDJmZjE5YiJ9fX0="}]}}}
      1'
```

if it won't work - reopen issue
